project:
  type: website
  

website:
  title: "Nicholas Bell, Ph.D."
  navbar:
    left:
      - href: "about.qmd"
        text: "About"
      - href: "teaching/teaching.qmd"
        text: "Teaching"
      - href: "https://www.powered-analysis.com/"
        text: "Powered Analysis"
        target: "_blank"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholasbellphd
      - icon: github
        href: https://github.com/nickybell

format:
  html:
    theme:
      - litera
      - html/njb.scss
    css: styles.css
    toc: false
    

